### ISSUE TITLE
DragDrop

### ISSUE THREAD

**Issue by NickWedzinga** [Bojzen-I-Mitten/thomas#13]
Dragging box/sphere/cube to hierarchy causes crash either inside GameObjectHierarchy.xaml.cs MouseMove() function or inside GameObjectHierarchy.xaml.cs hierarchy_Drop() function.

**Comment by Steve-Roper** [comment]
Inspector is not updated when selecting an object in the preview window.

**Comment by Steve-Roper** [comment]
Press enter to save variable value.

**Comment by ghost** [comment]
pleb oskar postar sina issues i andras issues
